config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get 'about', to: "home#about"
  get 'search', to: "home#search"
  post 'search', to: "home#search"

  devise_for :users, class_name: 'FormUser', :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations', invitations: 'invitations'}
  devise_scope :user do
    get '/users/auth/:provider/upgrade' => 'omniauth_callbacks#upgrade', as: :user_omniauth_upgrade
    get '/users/auth/:provider/setup', :to => 'omniauth_callbacks#setup'
    post 'login', to: 'devise/sessions#new'
    get 'logout', to: 'devise/sessions#destroy'
  end
  
  resources :communities do
    resources :memberships
    resources :projects do
      resources :pledges
      resources :musters
    end
    member do
      get :application
      post :apply
      get :applications
      post :approve
    end
  end

  resources :users do
    resources :check_ins
  end

  resources :labors do
    resources :ratings
  end

  resources :links
  resources :posts
  resources :images
end

app/models/muster.rb
class Muster < ApplicationRecord
  belongs_to :project
  has_many :users, :through => :labors
  has_many :images
  has_many :labors
  has_many :check_ins
  has_many :links
  
  def approved_images
    images.where(image_type:Image::APPROVED)
  end
  
  def own_labors(user)
    return labors.where(user_id:user.id).count
  end
  
  def rated_labors(user)
    labor_ids = labors.map{|l|l.id}
    Rating.where(user_id:user.id).where("labor_id IN (?)", labor_ids).count
  end

  def has_unrated_labors(user)
    return labors.count > rated_labors(user) + own_labors(user)
  end
  
  def to_s
    "#{description} at #{location} at #{start_time}"
  end
end

app/controllers/musters_controller.rb
class MustersController < ApplicationController
  before_action :set_muster, only: [:show, :edit, :update, :destroy]
  before_action :set_project
  before_action :check_project_admin, only: [:new, :create, :edit, :update, :destroy]

  # GET /musters
  # GET /musters.json
  def index
    @musters = Muster.all
  end

  # GET /musters/1
  # GET /musters/1.json
  def show
  end

  # GET /musters/new
  def new
    @muster = Muster.new
  end

  # GET /musters/1/edit
  def edit
  end

  # POST /musters
  # POST /musters.json
  def create
    @muster = Muster.new(muster_params)

    respond_to do |format|
      if @muster.save
        format.html { redirect_to [@community, @project, @muster], notice: 'Muster was successfully created.' }
        format.json { render :show, status: :created, location: @muster }
      else
        format.html { render :new }
        format.json { render json: @muster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /musters/1
  # PATCH/PUT /musters/1.json
  def update
    respond_to do |format|
      if @muster.update(muster_params)
        format.html { redirect_to [@community, @project, @muster], notice: 'Muster was successfully updated.' }
        format.json { render :show, status: :ok, location: @muster }
      else
        format.html { render :edit }
        format.json { render json: @muster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /musters/1
  # DELETE /musters/1.json
  def destroy
    @muster.destroy
    respond_to do |format|
      format.html { redirect_to [@project.community, @project], notice: 'Muster was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_project
      @project = @muster.project if @muster
      @project = Project.friendly.find(params[:project_id]) if @project.nil?
      @community = @project.community
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_muster
      @muster = Muster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def muster_params
      params[:muster][:project_id] = @project.id
      params.require(:muster).permit(:project_id, :location, :location_lat, :location_lon, :description, :notes, :start_time, :end_time)
    end
end

app/views/musters/_form.html.haml
= form_for [@community, @project, @muster] do |f|
  - if @muster.errors.any?
    .row
      #error_explanation
        %h2= "#{pluralize(@muster.errors.count, "error")} prohibited this muster from being saved:"
        %ul
          - @muster.errors.full_messages.each do |msg|
            %li= msg

  .row
    .col-md-4= f.label :location
    .col-md-4= f.text_field :location

  .row
    .col-md-4= f.label :description
    .col-md-4= f.text_area :description

  .row
    .col-md-4.col-md-4= f.label :start_time
    .col-md-4.col-md-4= f.datetime_field :start_time

  .row
    .col-md-4= f.label :end_time
    .col-md-4= f.datetime_field :end_time

  .row
    .col-md-4= f.submit 'Save'

app/views/musters/edit.html.haml
.container
  %h1.page-header Editing muster

  = render 'form'

app/views/musters/index.html.haml
.container
  %h1.page-header Listing musters
  
  -if current_user.is_admin_of? @project
    .row
      .col-md-2.col-md-offset-10= link_to 'New Muster', new_community_project_muster_path(@community, @project)

  .row
    .col-md-2 Location
    .col-md-2 Description
    .col-md-2 Time

  - @musters.each do |muster|
    .row
      .col-md-2= muster.location
      .col-md-2= muster.description
      .col-md-2= muster.start_time.to_s + " to " +muster.end_time.to_s
      .col-md-2= link_to 'View', [@community, @project, muster]
      -if current_user.is_admin_of? @project
        .col-md-2= link_to 'Edit', edit_community_project_muster_path(@community, @project, muster)
        .col-md-2= link_to 'Destroy', [@community, @project, muster], :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/musters/new.html.haml
.container
  %h1.page-header New muster for #{@project.name}

  = render 'form'
  

app/views/musters/show.html.haml
.container
  .row
    %b.col-md-4 Location:
    .col-md-4= @muster.location
  .row
    %b.col-md-4 Time:
    .col-md-4
      = @muster.start_time
      to
      = @muster.end_time
  .row
    %b.col-md-4 Description:
    .col-md-4= @muster.description
  .row
    %b.col-md-4 Notes:
    .col-md-4= @muster.notes
  
  .row
    %b.col-md-4 Pictures:
    .col-md-4= link_to "Add A Picture", new_image_path+"?muster_id=#{@muster.id}"
    %ul
      - @muster.approved_images.each do |image|
        %li=image_tag image.file.url(:thumb)
  
  .row
    %b.col-md-4 Labors:
    .col-md-4= link_to "View", labors_path+"?muster_id=#{@muster.id}"
  
  .col-md-4.col-md-offset-8= link_to 'Edit', edit_community_project_muster_path(@community, @project, @muster)