config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get 'about', to: "home#about"
  get 'search', to: "home#search"
  post 'search', to: "home#search"

  devise_for :users, class_name: 'FormUser', :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations', invitations: 'invitations'}
  devise_scope :user do
    get '/users/auth/:provider/upgrade' => 'omniauth_callbacks#upgrade', as: :user_omniauth_upgrade
    get '/users/auth/:provider/setup', :to => 'omniauth_callbacks#setup'
    post 'login', to: 'devise/sessions#new'
    get 'logout', to: 'devise/sessions#destroy'
  end
  
  resources :communities do
    resources :memberships
    resources :projects do
      resources :pledges
      resources :musters
    end
    member do
      get :application
      post :apply
      get :applications
      post :approve
    end
  end

  resources :users do
    resources :check_ins
  end

  resources :labors do
    resources :ratings
  end

  resources :links
  resources :posts
  resources :images
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @communities = Community.all
  end
  
  def about
  end

  def search
    @communities = Community.where("name LIKE ?", "%#{params[:q]}%")
    @projects = Project.where("name LIKE ?", "%#{params[:q]}%")
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.haml
.container
  %h1.page-header About The Help Bank
  
  %hr
  %h2.sub-header FAQ
  .row
    %b.col-md-3 How does it work?
    .col-md-9
      It's like Kickstarter, but for time instead of money ... and the time you put in is later paid back to you by others.
      %p
  .row
    .col-md-9.col-md-offset-3
      Join a community, find a project, and pledge your time to it. When you do the work, it's like putting your time into a bank;
      later, you can get community members to work on your own projects.
      %p

  %hr
  .row
    %b.col-md-3 So what all can I do here?
    .col-md-9
      It's pretty simple:
      %ul
        %li Sign up/in
        %li Join a community
        %li Pledge your time to a project
        %li If there's an official assembly to work on the project at a particular time / place, check in there / then
        %li Otherwise, just put in your hours on your own time
        %li Have your work approved and rated by the project admin(s)
        %li Rate the people you work with, if any, from one to five stars
        %li Collect stars for every hour you work
        %li Create your own projects, and use your stash of stars to pay back people who work on them

      If you want, you can create your own community, invite people to it, create projects, and be an admin, too!
      %p

  %hr
  .row
    %b.col-md-3 Can you give me an example?
    .col-md-9
      Sure! Consider Alice. She's really into bowling, so she creates the Excellent Bowling Community; invites Barry and Zika to join; launches the
      Polish The Gutters project, to improve the local hall; and pledges two hours of her own time.
      %p
    .col-md-9.col-md-offset-3
      Barry and Zika accept the invitations and each pledges two hours too. They hash out the details on the project's discussion page. After the work
      is done, everyone rates everyone else's work as four-star. Barry and Zika now each have eight stars -- four stars for each hour.
      %p
    .col-md-9.col-md-offset-3
      A month later, when Barry is moving, he creates his own personal project "Help Barry Move!" Alice and Zika pledge to help, and Barry uses his
      stash of stars to repay them for doing so.
 
  %hr
  .row
    %b.col-md-3 Is this a startup?
    .col-md-9
      Nope. It'd be a pretty bad one; there's no money in pledging time! This is purely a labor of love / an attempt to provide a useful tool to people.
      In fact, The Help Bank is itself a Help Bank community (how meta!) and this web site is one of its projects, built purely by unpaid volunteer contributors.


  %hr
  .row
    .col-md-9.col-md-offset-3
      %p

app/views/home/index.html.haml
.container
  %h1.page-header The Help Bank

  %ul
    %li= link_to 'About', "/about"
    -if current_user
      %li= link_to "Invite a new user", new_user_invitation_path
      -if current_user.communities.any?
        %li= link_to "Check in", new_user_check_in_path(current_user)
    -else
      %li= link_to 'Sign up', new_user_registration_path

  %h2.sub-header Communities and Projects

  -muster_ids = user_signed_in? ? current_user.labors.map{|l|l.muster_id}.compact.uniq : []
  %ul
    -@communities.each do |community|
      %li
        = link_to community.name, community
        - if user_signed_in? && current_user.is_member_of?(community)
          %ul
            -community.projects.each do |project|
              %li
                = link_to project, [community, project]
                %ul
                  -for muster in project.recent_musters_within(muster_ids)
                    -if muster.has_unrated_labors(current_user)
                      %li= link_to "Rate Labors: #{muster.location} #{muster.start_time}", labors_path+"?muster_id=#{muster.id}"

  -if current_user
    %hr
    %p= link_to 'Create a New Community', new_community_path
  

app/views/home/search.html.haml
%h1 The Help Bank

-if @communities.any?
  %h2 Communities
  %ul
    -@communities.each do |community|
      %li= link_to community.name, community

-if @projects.any?
  %h2 Projects
  %ul
    -@projects.each do |project|
      %li= link_to project, project

%hr
%p= link_to 'Create a New Community', new_community_path