config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get 'about', to: "home#about"
  get 'search', to: "home#search"
  post 'search', to: "home#search"

  devise_for :users, class_name: 'FormUser', :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations', invitations: 'invitations'}
  devise_scope :user do
    get '/users/auth/:provider/upgrade' => 'omniauth_callbacks#upgrade', as: :user_omniauth_upgrade
    get '/users/auth/:provider/setup', :to => 'omniauth_callbacks#setup'
    post 'login', to: 'devise/sessions#new'
    get 'logout', to: 'devise/sessions#destroy'
  end
  
  resources :communities do
    resources :memberships
    resources :projects do
      resources :pledges
      resources :musters
    end
    member do
      get :application
      post :apply
      get :applications
      post :approve
    end
  end

  resources :users do
    resources :check_ins
  end

  resources :labors do
    resources :ratings
  end

  resources :links
  resources :posts
  resources :images
end

app/models/community.rb
class Community < ApplicationRecord
  has_many :memberships
  has_many :projects
  has_many :posts
  has_many :links
  include FriendlyId
  friendly_id :name, :use => :slugged
  
  APPROVAL_REQUIRED = 0
  AUTO_APPROVE_INVITEES = 1
  AUTO_APPROVE = 2

  def admins
    memberships.where("role_id = ?", Membership::ADMIN)
  end

  def to_s
    name
  end
  
  def members_and_admins
    Membership.where(community_id: self.id).where("role_id IN (?)", [Membership::MEMBER, Membership::ADMIN])
  end

  def pending_applications
    Membership.where(community_id: self.id).where(role_id: Membership::APPLICANT)
  end

  def declined_applications
    Membership.where(community_id: self.id).where(role_id: Membership::DECLINED)
  end
  
  def root_posts
    posts.where(reply_to_post_id:nil)
  end
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :set_community, except: [:index, :new, :create]
  before_action :check_community_member, except: [:index, :show, :new, :create, :application, :apply]
  before_action :check_community_admin, only: [:edit, :update, :destroy, :applications, :approve]

  # GET /communities
  # GET /communities.json
  def index
    redirect_to "/"
  end

  # GET /communities/1
  # GET /communities/1.json
  def show
  end
  
  def application
    redirect_to "/" if current_user.nil?
  end
  
  def apply
    existing = Membership.find_by_user_id_and_community_id(current_user.id, @community.id)
    if existing.nil?
      application_info = params[:application_info]
      membership = Membership.create(user_id: current_user.id, community_id: @community.id, role_id: Membership::APPLICANT, application_info:application_info)
      if Community::AUTO_APPROVE == @community.community_type_id
        membership.update_column :role_id, Membership::MEMBER
        flash[:notice] = "Application auto-approved!!"
        redirect_to @community and return
      end
    else
      flash[:notice] = "You already have the status: #{existing.description} for this community."
    end
    redirect_to "/"
  end
  
  def applications
    @pending = @community.pending_applications
    @declined = @community.declined_applications
  end
  
  def approve
    membership = Membership.find(params[:membership_id])
    membership.role_id = Membership::MEMBER
    membership.save!
    redirect_to community_path(@community) and return
  end

  # GET /communities/new
  def new
    @community = Community.new
  end

  # GET /communities/1/edit
  def edit
  end

  # POST /communities
  # POST /communities.json
  def create
    @community = Community.new(community_params)

    respond_to do |format|
      if @community.save
        Membership.create(user_id: current_user. id, role_id: Membership::ADMIN, community_id: @community.id)
        format.html { redirect_to @community, notice: 'Community was successfully created.' }
        format.json { render :show, status: :created, location: @community }
      else
        format.html { render :new }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /communities/1
  # PATCH/PUT /communities/1.json
  def update
    respond_to do |format|
      if @community.update(community_params)
        format.html { redirect_to @community, notice: 'Community was successfully updated.' }
        format.json { render :show, status: :ok, location: @community }
      else
        format.html { render :edit }
        format.json { render json: @community.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communities/1
  # DELETE /communities/1.json
  def destroy
    @community.destroy
    respond_to do |format|
      format.html { redirect_to communities_url, notice: 'Community was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_community
      @community = Community.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def community_params
      params.require(:community).permit(:name, :description, :notes, :community_type_id, :stars_to_create_a_project)
    end
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/views/communities/_form.html.haml
= form_for @community do |f|
  - if @community.errors.any?
    #error_explanation
      %h2= "#{pluralize(@community.errors.count, "error")} prohibited this community from being saved:"
      %ul
        - @community.errors.full_messages.each do |msg|
          %li= msg

  .row
    .col-md-4= f.label :name
    .col-md-4= f.text_field :name

  .row
    .col-md-4= f.label :description
    .col-md-4= f.text_area :description

  .row
    .col-md-4= f.label :approval_rules
    - options = [["Approval Required", Community::APPROVAL_REQUIRED], ["Auto Approve Invitees", Community::AUTO_APPROVE_INVITEES], ["Auto Approve Applications", Community::AUTO_APPROVE]]
    .col-md-4= f.select :community_type_id, options_for_select(options)

  .row
    .col-md-4= f.label "Stars to create a private project"
    .col-md-4= f.number_field :stars_to_create_a_project

  .row
    .col-md-4.col-md-offset-4= f.submit 'Save'

app/views/communities/application.html.haml
.container
  %h3 Application to #{@community.name}
  
  = form_tag("/communities/#{@community.id}/apply", method: :post) do
    = text_area_tag :application_info, "", {rows: 10, cols:60, :placeholder => "Tell the community something about yourself"}
    %br
    = submit_tag 'Apply'

app/views/communities/applications.html.haml
%h3 Pending Applications

%ul
-@pending.each do |membership|
  %li
    =membership.user
    =link_to "View", community_membership_path(@community, membership)
    =link_to "Approve", approve_community_path(@community)+"?membership_id=#{membership.id}", :method => :post

%h3 Declined Applications
%ul
-@declined.each do |membership|
  %li
    =membership.user

app/views/communities/edit.html.haml
.container
  %h1.page-header= @community

  = render 'form'

app/views/communities/index.html.haml
%h1 Listing communities

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @communities.each do |community|
      %tr
        %td= community.name
        
        -if current_user.is_member_of? community
          %td= link_to 'Show', community
        -else
          %td= link_to 'Apply', application_community_path(community)
        -if current_user.is_admin_of? community
          %td= link_to 'Edit', edit_community_path(community)
          %td= link_to 'Destroy', community, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Community', new_community_path

app/views/communities/new.html.haml
.container
  %h1.page-header New community

  = render 'form'

app/views/communities/show.html.haml
.jumbotron
  .container
    %h1= @community.name
    %p= @community.description
    -if current_user_admin_of? @community
      %p= link_to 'Edit', edit_community_path(@community)

.container
  .row
    .col-md-4
      %h2.sub-header Projects
      - if @community.projects.empty?
        %p None yet
        -if user_signed_in? and current_user.is_admin_of?(@community)
          =link_to "Create new project", new_community_project_path(@community)
      - else
        %ul
          -@community.projects.each do |project|
            %li= link_to project, community_project_path(@community, project)
  
    -if current_user_member_of? @community
      .col-md-4
        %h2.sub-header Members
        %p
          = @community.members_and_admins.count
          = link_to "View", community_memberships_path(@community)
        %p
          = link_to "Invite a new member", "/users/invitation/new?community_id=#{@community.id}"
    -else
      .col-md-4
        %h2.sub-header Apply for Membership
        %p
          = link_to "Apply", application_community_path(@community)
  
    -if current_user_admin_of? @community
      .col-md-4
        %h2.sub-header Applications
        %p
          = @community.pending_applications.count
          = link_to "View", applications_community_path(@community)

  %h2.sub-header Discussion
  -if user_signed_in? && current_user.is_member_of?(@community)
    .row#edit-row
      .col-md-12
        %h3#pre-form.sub-header=link_to "Start a new discussion", "javascript:reply_to('');"
        %form{action: "/posts?community_id=#{@community.id}", method: "post", id:"edit-form", style:"#{@community.posts.empty? ? '' : 'display:none;'}"}
          =hidden_field_tag :authenticity_token, form_authenticity_token
          =hidden_field_tag "post[community_id]", @community.id
          =hidden_field_tag "post[content]", '', id:"trix"
          =hidden_field_tag "post[reply_to_post_id]", '', id:"reply_to_post_id"
          %trix-editor{input:"trix"}
          =submit_tag "Post"
  
  -for post in @community.root_posts
    %hr
    .row{id:"post-#{post.id}", name:"post-#{post.id}"}
      %b.col-md-1.col-md-offset-1= post.user
      .col-md-1= avatar_for(post.user)
      .col-md-8!= post.content
      -if user_signed_in?
        -if current_user.id == post.user_id
          .col-md-1= link_to "Delete", post, :method => :delete, :data => { :confirm => 'Are you sure?' }
        -elsif current_user.is_member_of?(@community)
          .col-md-1= link_to "Reply", "javascript:reply_to(#{post.id});"
    -for reply in post.replies
      .row{id:"post-#{reply.id}", name:"post-#{reply.id}"}
        %b.col-md-1.col-md-offset-2= reply.user
        .col-md-1= avatar_for(reply.user)
        .col-md-7!= reply.content
        -if user_signed_in? and current_user.id == reply.user_id
          .col-md-1= link_to "Delete", reply, :method => :delete, :data => { :confirm => 'Are you sure?' }

:javascript
  var reply_to = function(post_id) {
    $("#reply_to_post_id").val(post_id);
    form = $("#edit-form").detach();
    if (post_id == '') {
      form.insertAfter("#pre-form");
    } else {
      form.insertAfter("#post-"+post_id);
    }
    $("#edit-form").show();
  }