config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get 'about', to: "home#about"
  get 'search', to: "home#search"
  post 'search', to: "home#search"

  devise_for :users, class_name: 'FormUser', :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations', invitations: 'invitations'}
  devise_scope :user do
    get '/users/auth/:provider/upgrade' => 'omniauth_callbacks#upgrade', as: :user_omniauth_upgrade
    get '/users/auth/:provider/setup', :to => 'omniauth_callbacks#setup'
    post 'login', to: 'devise/sessions#new'
    get 'logout', to: 'devise/sessions#destroy'
  end
  
  resources :communities do
    resources :memberships
    resources :projects do
      resources :pledges
      resources :musters
    end
    member do
      get :application
      post :apply
      get :applications
      post :approve
    end
  end

  resources :users do
    resources :check_ins
  end

  resources :labors do
    resources :ratings
  end

  resources :links
  resources :posts
  resources :images
end

app/models/labor.rb
class Labor < ApplicationRecord
  belongs_to :user
  belongs_to :project
  belongs_to :pledge, required: false
  belongs_to :muster, required: false
  has_many :ratings
  
  REJECTED = -1
  SUBMITTED = 0
  APPROVED = 1
  
  def string_for_status
    return "Rejected" if status == -1
    return "Submitted" if status == 0
    return "Approved" if status == 1
  end
  
  def average_rating
    ratings.reduce(0){|sum,r|sum + r.stars}.to_f / ratings.count
  end
  
  def check_ins
    muster ? muster.check_ins.where(user_id:user.id) : []
  end

  def to_s
    "#{hours} hours #{user}"
  end
end

app/controllers/labors_controller.rb
class LaborsController < ApplicationController
  before_action :set_labor, only: [:show, :edit, :update, :destroy]
  before_action :set_muster
  before_action :set_project
  before_action :set_user

  # GET /labors
  # GET /labors.json
  def index
    @labors = @muster.labors if @muster.present?
    @labors = @project.labors if @labors.nil? && @project.present? && @user.is_admin_of?(@project)
    @labors = @user.labors if @labors.nil?
  end

  # GET /labors/1
  # GET /labors/1.json
  def show
  end

  # GET /labors/new
  def new
    @labor = Labor.new
  end

  # GET /labors/1/edit
  def edit
  end

  # POST /labors
  # POST /labors.json
  def create
    @labor = Labor.new(labor_params)

    @pledge = @user.first_unfulfilled_pledge_for(@project)
    @labor.pledge_id = @pledge.id if @pledge

    @muster = @labor.user.muster_for(@project, @labor.start_time)
    @labor.muster_id = @muster.id if @muster

    if @project.is_private?
      @pledge = @user.first_unfulfilled_pledge_for(@project)
      if !@pledge
        flash[:notice] = "No previous pledge found. You cannot update unpledged hours for a private project"
        render :new and return
      end
      if @labor.hours > @pledge.hours
        flash[:notice] = "You cannot submit more than your pledged #{@pledge.hours} hours"
        render :new and return
      end
    end

    respond_to do |format|
      if @labor.save
        format.html { redirect_to [@community, @project], notice: 'Labor was successfully created.' }
        format.json { render :show, status: :created, location: @labor }
      else
        format.html { render :new }
        format.json { render json: @labor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /labors/1
  # PATCH/PUT /labors/1.json
  def update
    lparams = labor_params
    respond_to do |format|
      # set pledge and muster correctly
      if @labor.status == Labor::SUBMITTED && lparams[:status].to_i==Labor::APPROVED && current_user.is_admin_of?(@labor.project)

        #does this work match a previous pledge?
        @pledge = @user.first_unfulfilled_pledge_for(@project)
        lparams[:pledge_id] = @pledge.id if @pledge
        
        #does this work match a muster to which the user checked in?
        start_time = DateTime.parse(lparams[:start_time]) if lparams[:start_time]
        @muster = @labor.user.muster_for(@project, start_time ? start_time : @labor.start_time)
        lparams[:muster_id] = @muster.id if @muster
      end
      
      if @project.is_private? && current_user.is_admin_of?(@project)
        stars = params.permit(:rating)[:rating]
        available_stars = current_user.membership_for(@project.community).total_stars
        if stars.to_i * @labor.hours > available_stars
          render :new and return
        end
      end

      if @labor.update(lparams)
        rparam = params.permit(:rating)
        if rparam.has_key?(:rating) and current_user.is_admin_of?(@labor.project)
          stars = rparam[:rating]
          existing = current_user.ratings.where(labor_id:@labor.id)
          existing.last.update_column(:stars, stars) if existing.any? and existing.last.stars != stars.to_i
          Rating.create(stars:stars, labor:@labor, user_id:current_user.id) if existing.empty?
        end
        format.html { redirect_to [@community, @project], notice: 'Labor was successfully updated.' }
        format.json { render :show, status: :ok, location: @labor }
      else
        format.html { render :edit }
        format.json { render json: @labor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /labors/1
  # DELETE /labors/1.json
  def destroy
    redirect_to "/" and return unless current_user.is_admin_of?(@labor.project) or current_user.id==@labor.user.id
    @labor.destroy
    respond_to do |format|
      format.html { redirect_to [@community, @project], notice: 'Labor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = @labor.user if @labor and @labor.user
      @user = current_user if @user.nil?
    end

    def set_muster
      @muster = @labor.muster if @labor.present?
      @muster = Muster.find_by_id(params[:muster_id]) if @muster.nil?
      if @muster.present?
        redirect_to "/" unless @muster.users.include?(current_user) or current_user.is_admin_of?(@muster.project)
      end
    end
    
    def set_project
      @project = @labor.project if @labor
      @project = @muster.project if @muster
      @project = Project.find_by_id(params[:labor][:project_id]) if @project.nil? and params[:labor]
      @project = Project.find_by_id(params[:project_id]) if @project.nil?
      redirect_to "/" and return if @project and not current_user.is_member_of?(@project)
      @community = @project.community
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_labor
      @labor = Labor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def labor_params
      params[:labor][:user_id] = @user.id
      params[:labor].delete(:status) unless current_user.is_admin_of?(@project)
      params.require(:labor).permit(:user_id, :project_id, :muster_id, :pledge_id, :status, :start_time, :hours, :notes)
    end
end

app/helpers/labors_helper.rb
module LaborsHelper
end

app/views/labors/_form.html.haml
= form_for @labor do |f|
  - if @labor.errors.any?
    #error_explanation
      %h2= "#{pluralize(@labor.errors.count, "error")} prohibited this labor from being saved:"
      %ul
        - @labor.errors.full_messages.each do |msg|
          %li= msg

  = f.hidden_field :project_id, :value => @project.id

  .row
    .col-md-4= f.label :start_time
    .col-md-4= f.datetime_field :start_time

  .row
    .col-md-4= f.label :hours
    .col-md-4= f.number_field :hours

  .row
    .col-md-4= f.label :notes
    .col-md-4= f.text_area :notes

  - if current_user && (current_user.is_admin? || (@labor.project && @labor.project.community.admins.map{|m|m.user_id}.include?(current_user.id)))
    .row
      .col-md-4= f.label :status
      .col-md-4= f.select :status, [["Unverified", 0], ["Verified", 1]]
  
    .row
      .col-md-4= f.label :rating
      - options = [["*****",5],["****",4],["***",3],["**",2],["*",1]]
      - previous = current_user.ratings.where(labor_id:@labor.id)
      - selected_val = previous.any? ? 5-previous.last.stars : 2 #default to 3 stars
      - selected = options.index{|b|b[1]==selected_val}
      .col-md-4= select_tag :rating, options_for_select(options, selected)

  .row
    .col-md-4= f.submit 'Save'

app/views/labors/edit.html.haml
.container
  %h1.page-header Editing labor for #{@user.to_s} on #{@project.name}

  = render 'form'
  
  = link_to 'Show', @labor
  \|
  = link_to 'Back', labors_path

app/views/labors/index.html.haml
-project_arg = @project ? "?project_id="+@project.id.to_s : ''
.container
  %h1.page-header Listing labors for #{@project ? @project.name+":" : @user.to_s} #{@muster ? " at "+@muster.to_s : ''}

  - if @project
    .row
      .col-md-2.col-md-offset-10= link_to 'New Labor', new_labor_path+project_arg

  .row
    %b.col-md-2= @project ? "User" : "Project"
    %b.col-md-2 Hours
    %b.col-md-2 Status

  - @labors.each do |labor|
    .row
      .col-md-2= @project ? display_user(labor.user) : labor.project.name
      .col-md-2= labor.hours
      .col-md-2= labor.string_for_status
      .col-md-2
        = link_to 'View', labor
        |
        - if current_user.id == labor.user_id or current_user.is_admin_of?(@project)
          = link_to 'Edit', edit_labor_path(labor)
          |
          = link_to 'Destroy', labor_path(labor)+project_arg, :method => :delete, :data => { :confirm => 'Are you sure?' }
        - else
          = link_to "Rate", new_labor_rating_path(labor)

app/views/labors/new.html.haml
.container
  %h1.page-header New labor for #{@user.to_s} on #{@project.name}

  = render 'form'

app/views/labors/show.html.haml
.container
  .row
    %b.col-md-4 Hours:
    .col-md-4= @labor.hours
  .row
    %b.col-md-4 Notes:
    .col-md-4= @labor.notes
  .row
    %b.col-md-4 Status:
    .col-md-4= @labor.status
  - if @labor.pledge
    .row
      %b.col-md-4 Pledge:
      .col-md-4= link_to "pledge", [@project.community, @project, @labor.pledge]
  - if @labor.muster
    .row
      %b.col-md-4 Muster:
      .col-md-4= link_to "muster", [@project.community, @project, @labor.muster]
  - if @labor.check_ins.any?
    .row
      %b.col-md-4 Check-in(s):
      .col-md-4= link_to "check-ins", user_check_ins_path(@user)
  
  .row
    %b.col-md-4 Ratings:
    .col-md-4= link_to 'View', labor_ratings_path(@labor)
  
  - if current_user.id == @labor.user_id or current_user.is_admin_of?(@labor.project)
    .col-md-4.col-md-offset-8= link_to 'Edit', edit_labor_path(@labor)